### ISSUE TITLE
SUT fails to comeup after running command java -jar activeadmin-demo.war

### ISSUE THREAD

**Issue by 2vireddy** [getgauge-examples/python-selenium#1]
Below error is displayed after launching localhost url

Request Method: | GET
-- | --
http://localhost:8080/

load error: /private/var/folders/4g/w2brbfg11hd3s47j7zntltx80000gn/T/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-7260948541329093950.dir/webapp/WEB-INF/config/environment -- java.lang.IllegalAccessException: Can not set static final boolean field javax.crypto.JceSecurity.isRestricted to java.lang.Boolean from org/jruby/RubyKernel.java:961:in `require' from uri:classloader:/jruby/rack/rails/environment3.rb:25:in `load_environment' from uri:classloader:/jruby/rack/rails_booter.rb:83:in `load_environment' from <script>:1:in `<main>'

You're seeing this error because you use JRuby::Rack::ErrorApp::ShowStatus.

**Comment by NivedhaSenthil** [comment]
Can you provide more details on how you are trying to launch demo app and more details regarding your environments ?

**Comment by 2vireddy** [comment]
I am trying to launch the app by executing the command java -jar activeadmin-demo.war on mac terminal window.

Below are environment details.
java --version
java 9.0.1
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

python --version
Python 2.7.10

name
Darwin
